# Spring Configuration
spring:
  application:
    name: @project.name@
  main:
    allow-bean-definition-overriding: true

# Swagger Documentation
swagger:
  service:
    version: "1.0.0"
    title: ${spring.application.name}
    description: "Skeleton app swagger"

zuul:
  igoredServices: '*'
  routes:
    customer-app:
      path: /customers/**
      serviceId: customer-app
      strip-prefix: false

ribbon:
  eureka:
    enabled: false

customer-app:
  ribbon:
    listOfServers: localhost:8081